name: test-discord-bot
workers:
- name: test-discord-bot
  environment_slug: python
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: ShivaniKumar1/test-discord-bot
  build_command: "pip install -r requirements.txt"
  run_command: "python discord_bot.py"
  instance_count: 1
  envs:
    - key: DISCORD_TOKEN
      value: <REQUIRED>
      type: SECRET
