name: template-discord-bot-worker
services:
- name: template-discord-bot-worker
  environment_slug: python
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/template-discord-bot-worker
  build_command: "pip install -r requirements.txt"
  run_command: "python discord_bot.py"
  run_type: worker
  envs:
    - key: DISCORD_TOKEN
      value: <REQUIRED>
      type: secret
